source 'https://rubygems.org'

if ENV['REAR_ENV'] == 'dev'
  gems_root = File.expand_path('../../../../..', __FILE__)
  gem 'e',    path: gems_root + '/espresso'
  gem 'rear', path: gems_root + '/rear/rear'
  gem 'rear-ace', path: gems_root + '/rear/rear-ace'
else
  gem 'rear'
  gem 'rear-ace'
end

gem 'thin'
