source 'https://rubygems.org'

if %x[hostname].strip == 'slivu'
  gems_root = File.expand_path('../../../../..', __FILE__)
  gem 'e',    path: gems_root + '/espresso'
  gem 'e-periphery', path: gems_root + '/e-periphery'
  gem 'rear', path: gems_root + '/rear/rear'
else
  gem 'rear'
end
gem 'thin'
