source 'https://rubygems.org'

if ENV['REAR_ENV'] == 'dev'
  gems_root = File.expand_path('../../../../..', __FILE__)
  gem 'e',    path: gems_root + '/espresso'
  gem 'e-periphery', path: gems_root + '/e-periphery'
  gem 'rear', path: gems_root + '/rear/rear'
else
  gem 'rear'
end

gem 'thin'
gem 'data_mapper'
gem 'dm-mysql-adapter'
